### ISSUE TITLE
absolute paths are not found

### ISSUE THREAD

**Issue by scottwio** [stringham/move-ts#10]
Typescript allows you to us absolute paths to references imports. These however do not get detected by this plugin. Is there any way you could find and change these paths.

    import { PromotionEffect } from 'app/shared/store-effects/promotions.effect';

Thanks for the plugin, so helpful

**Comment by stringham** [comment]
Yes, if the module resolution is set to "classic" then typescript will look for other ways to resolve paths other than the relative path.

However, it's more complicated than just being "absolute" from the root of the project. See https://www.typescriptlang.org/docs/handbook/module-resolution.html#classic for the description.

Currently, this extension resolves and updates relative paths with a combination of regular expressions. In order to update imports for their "classic" module resolution it would either require a lot of work, or potentially may need an API from the TypeScript team to be implemented: https://github.com/Microsoft/TypeScript/issues/6487 .

**Comment by stringham** [comment]
Added a user setting in version 1.9.0. Set `movets.relativeToTsconfig` to `true` to enable.
